[project]
name = "bookkeeping-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "transformers>=4.57.1",
    "vllm>=0.11.0",
]
